# Generated by Django 5.0.7 on 2024-11-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_sellers_pizza_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers',
            name='address',
            field=models.CharField(default='none', max_length=150),
        ),
        migrations.AddField(
            model_name='sellers',
            name='city',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='sellers',
            name='name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='sellers',
            name='state',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
