# Generated by Django 5.0.7 on 2024-11-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_sellers_address_sellers_city_sellers_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
