# Generated by Django 5.0.7 on 2024-11-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_sellers_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='descrip',
            field=models.CharField(default='Pizza', max_length=100),
        ),
    ]
