# Generated by Django 5.0.7 on 2024-11-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_pizza_descrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='ex_img',
            field=models.FileField(default='images/image2.png', upload_to='images'),
        ),
    ]
