# Generated by Django 5.0.7 on 2024-11-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_temp_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_order',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='temp_order',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
