# Generated by Django 5.0.7 on 2024-11-11 15:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_temp_order_date_temp_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_order',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
