# Generated by Django 5.0.7 on 2024-11-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_alter_temp_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_order',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='temp_order',
            name='time',
            field=models.TimeField(),
        ),
    ]
