# Generated by Django 5.0.7 on 2024-11-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_alter_temp_order_date_alter_temp_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='temp_order',
            name='time',
        ),
    ]
