# Generated by Django 5.0.7 on 2024-11-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_remove_temp_order_date_remove_temp_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
